version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: softwave_db
      MYSQL_USER: softwave
      MYSQL_PASSWORD: softwave123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: eclipse-temurin:21-jdk
    container_name: backend_softwave
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/softwave_db
      SPRING_DATASOURCE_USERNAME: softwave
      SPRING_DATASOURCE_PASSWORD: softwave123
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "BackendSoftWave.jar"]

volumes:
  db_data:
